# Generated by Django 2.2.6 on 2019-10-21 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_guest_trip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='user',
        ),
        migrations.AddField(
            model_name='trip',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='trips_created', to='app.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='guest',
            field=models.ManyToManyField(related_name='trips_guest_of', to='app.User'),
        ),
        migrations.DeleteModel(
            name='Guest',
        ),
    ]
